# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/.Xil/Vivado-35616-DESKTOP-SV406LK/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {{C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new}} {
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/alu_control_ex.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/alu_ex.v}
      {C:/Users/admin/Desktop/4203/IF STAGE/4300lab1a.srcs/sources_1/new/control_unit.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/data_memory.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/ex_mem_reg.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/ex_stage.v}
      {C:/Users/admin/Desktop/4203/IF STAGE/4300lab1a.srcs/sources_1/new/id_ex_reg.v}
      {C:/Users/admin/Desktop/4203/IF STAGE/4300lab1a.srcs/sources_1/new/id_stage.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/if_id_reg.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/if_stage.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/incr4.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/inst_memory.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/mem_and_gate.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/mem_stage.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/mem_wb_reg.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/mux2_ex.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/mux2to1.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/pc_reg.v}
      {C:/Users/admin/Desktop/4203/IF STAGE/4300lab1a.srcs/sources_1/new/pipeline_top.v}
      {C:/Users/admin/Desktop/4203/IF STAGE/4300lab1a.srcs/sources_1/new/reg_file.v}
      {C:/Users/admin/Desktop/4203/IF STAGE/4300lab1a.srcs/sources_1/new/sign_extend.v}
      {C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/4300lab1a.srcs/sources_1/new/wb_stage.v}
      {C:/Users/admin/Desktop/4203/IF STAGE/4300lab1a.srcs/sources_1/new/pipeline_top_tb.v}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top pipeline_top_tb
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/admin/Documents/GitHub/ECE-4300-Computer-Architecture-Implementing-a-Datapath-in-Verilog/IF + ID + EX + MEM + WB/.Xil/Vivado-35616-DESKTOP-SV406LK/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
